# Generated by Django 2.2.26 on 2022-04-12 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parallel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='expiretime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 2, 14, 10, 881673), verbose_name='Expire Time'),
        ),
    ]
