# Generated by Django 2.2.26 on 2022-04-12 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parallel', '0003_auto_20220412_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='expiretime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 9, 37, 26, 261171), verbose_name='Expire Time'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='apptype',
            field=models.CharField(choices=[('recording', 'recording'), ('parallel', 'parallel'), ('accessibility', 'accessibility')], default='parallel', max_length=64, verbose_name='Application Type'),
        ),
    ]
