# Generated by Django 2.2.26 on 2022-06-16 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parallel', '0004_auto_20220412_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='expiretime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 14, 11, 22, 38, 696300), verbose_name='Expire Time'),
        ),
    ]
