# Generated by Django 2.2.26 on 2022-03-18 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('host', models.CharField(default='', max_length=256, verbose_name='Host FQDN/IP')),
                ('index', models.IntegerField(blank=True, default=-1, verbose_name='Host Index Number')),
                ('port', models.IntegerField(blank=True, default=0, verbose_name='Host Port')),
                ('deploypath', models.CharField(blank=True, default='', max_length=256, verbose_name='Deployment Path')),
                ('consoleid', models.IntegerField(blank=True, default=0, verbose_name='Console ID')),
                ('apptype', models.CharField(default='', max_length=64, verbose_name='User Name')),
                ('status', models.CharField(blank=True, choices=[('running', 'running'), ('stopped', 'stopped')], default='stopped', max_length=64, verbose_name='Status')),
                ('pooltype', models.CharField(default='localhost', max_length=256, verbose_name='Pool Type')),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipaddr', models.CharField(default='', max_length=64, verbose_name='FQDN/IP')),
                ('sshport', models.IntegerField(blank=True, default=22, verbose_name='SSH Port')),
                ('username', models.CharField(default='root', max_length=64, verbose_name='User Name')),
                ('password', models.CharField(default='v', max_length=64, verbose_name='Password')),
                ('deployroot', models.CharField(blank=True, default='/root', max_length=256, verbose_name='Deployment Root')),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('maintainance', 'maintainance')], default='maintainance', max_length=64, verbose_name='Status')),
                ('capacity', models.IntegerField(blank=True, default=20, verbose_name='Capacity')),
                ('startport', models.IntegerField(blank=True, default=6950, verbose_name='Start Port')),
                ('current_num', models.IntegerField(blank=True, default=0, verbose_name='Deployed Number')),
                ('deployment', models.CharField(blank=True, default='', max_length=256, verbose_name='Deployment')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
            },
        ),
    ]
