# Generated by Django 2.2.16 on 2022-01-20 05:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=0, verbose_name='Test ID')),
                ('run_id', models.IntegerField(default=0, verbose_name='Run ID')),
                ('user', models.CharField(default='', max_length=64, verbose_name='User')),
                ('product', models.CharField(default='', max_length=255, verbose_name='Product')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('template', models.CharField(default='', max_length=255, verbose_name='Template')),
                ('path', models.CharField(default='', max_length=255, verbose_name='Script Path')),
                ('events', models.TextField(blank=True, default='', null=True, verbose_name='User Events')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('createtime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Create Time')),
                ('lastupdate', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
                'db_table': 'script_script',
            },
        ),
    ]
